stages:
  - install
  - Zegarownia
  - Fabryka
  - Watchard
  - Hodinkovna-CZ
  - Hodinkovna-SK
  - Eceasuri
  - Eorak
  - Send-report

variables:
  HEADLESS: "true"

cache:
  paths:
    - .cache
    - venv/

before_script:
  - apt-get update && apt-get install -y python3-venv
  - python -V
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

default:
  image: mcr.microsoft.com/playwright/python:v1.44.0-jammy
  tags:
    - superpharm
  artifacts:
    when: always
    expire_in: 3 DAYS
    paths:
      - screenshots/
      - /allure-results

.pipeline-branch-model:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: manual
  allow_failure: true

install-dependencies:
  stage: install
  script:
    - pip install pytest playwright
    - playwright install

Zegarownia-orders:
  extends: .pipeline-branch-model
  stage: Zegarownia
  script:
    - source venv/bin/activate
    - pytest tests/Zegarownia/Orders/GuestUser/ --env=prod --alluredir=allure_results

Fabryka-orders:
  extends: .pipeline-branch-model
  stage: Fabryka
  script:
    - source venv/bin/activate
    - pytest tests/Fabrykazegarkow/Orders/GuestUser/ --env=prod --alluredir=allure_results

Hodinkovna-CZ-orders:
  extends: .pipeline-branch-model
  stage: Hodinkovna-CZ
  script:
    - source venv/bin/activate
    - pytest tests/HodinkovnaCZ/Orders/GuestUser/ --env=prod --alluredir=allure_results

Hodinkovna-SK-orders:
  extends: .pipeline-branch-model
  stage: Hodinkovna-SK
  script:
    - source venv/bin/activate
    - pytest tests/HodinkovnaSK/Orders/GuestUser/ --env=prod --alluredir=allure_results

Eceasuri-orders:
  extends: .pipeline-branch-model
  stage: Eceasuri
  script:
    - source venv/bin/activate
    - pytest tests/Eceasuri/Orders/GuestUser/ --env=prod --alluredir=allure_results

Eorak-orders:
  extends: .pipeline-branch-model
  stage: Eorak
  script:
    - source venv/bin/activate
    - pytest tests/Eorak/Orders/GuestUser/ --env=prod --alluredir=allure_results

Submit-finished-report:
  extends: .pipeline-branch-model
  stage: Send-report
  before_script:
    - date
    - apt-get update && apt-get install -y wget jq
  needs:
    - job: Zegarownia-orders
      artifacts: true
  script:
    - ./allure-server/allure-push.sh ${CI_PIPELINE_ID}
