stages:
  - install
  - Store-1
  - Store-2
  - Send-report

variables:
  HEADLESS: "true"

cache:
  paths:
    - .cache
    - venv/

before_script:
  - apt-get update && apt-get install -y python3-venv
  - python -V
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

default:
  image: mcr.microsoft.com/playwright/python:v1.44.0-jammy
  tags:
    - runner
  artifacts:
    when: always
    expire_in: 3 DAYS
    paths:
      - screenshots/
      - allure-results

.pipeline-branch-model:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: manual
  allow_failure: true

.pipeline-test:
  extends: .pipeline-branch-model
  script:
    - source venv/bin/activate
    - pytest $STORE_TEST_PATH --env=$ENVIRONMENT --alluredir=allure-results

install-dependencies:
  stage: install
  script:
    - pip install pytest playwright
    - playwright install

Store-1-orders:
  extends: .pipeline-test
  stage: Store-1
  variables:
    STORE_TEST_PATH: "tests/Store1/Orders/GuestUser/"

Store-1-login:
  extends: .pipeline-test
  stage: Store-1
  variables:
    STORE_TEST_PATH: "tests/Store1/User/Login"

Store-1-sign-in:
  extends: .pipeline-test
  stage: Store-1
  variables:
    STORE_TEST_PATH: "tests/Store1/User/SignIn"

Store-2-orders:
  extends: .pipeline-test
  stage: Store-2
  variables:
    STORE_TEST_PATH: "tests/Store2/Orders/GuestUser/"

Store-2-login:
  extends: .pipeline-test
  stage: Store-2
  variables:
    STORE_TEST_PATH: "tests/Store2/User"

Store-2-sign-in:
  extends: .pipeline-test
  stage: Store-2
  variables:
    STORE_TEST_PATH: "tests/Store2/User/SignIn"

Submit-finished-report:
  stage: Send-report
  before_script:
    - date
    - apt-get update && apt-get install -y wget jq
  script:
    - chmod +x ./allure-server/allure-push.sh
    - ./allure-server/allure-push.sh ${CI_PIPELINE_ID} 
  dependencies:
    - Store-1-orders
    - Store-1-login
    - Store-1-sign-in
    - Store-2-orders
    - Store-2-login
    - Store-2-sign-in

