stages:
  - install
  - Zegarownia
  - Send-report

variables:
  HEADLESS: "true"

cache:
  paths:
    - .cache
    - venv/

before_script:
  - apt-get update && apt-get install -y python3-venv
  - python -V
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

default:
  image: mcr.microsoft.com/playwright/python:v1.44.0-jammy
  tags:
    - superpharm
  artifacts:
    when: always
    expire_in: 3 DAYS
    paths:
      - screenshots/
      - target/allure-results/

.pipeline-branch-model:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: manual
  allow_failure: true

install-dependencies:
  stage: install
  script:
    - pip install pytest playwright
    - playwright install

Zegarownia-orders:
  extends: .pipeline-branch-model
  stage: Zegarownia
  script:
    - source venv/bin/activate
    - pytest tests/Fabrykazegarkow/Orders/GuestUser/individual_test/test_buy_product_by_courier_dhl_Blik.py --env=stage --alluredir=allure_results

Submit-finished-report:
  extends: .pipeline-branch-model
  stage: Send-report
  before_script:
    - date
    - apt-get update && apt-get install -y wget jq
  needs:
    - Zegarownia-orders
  script:
    - ./allure-server/allure-push.sh ${CI_PIPELINE_ID}
