stages:
  - install
  - Zegarownia

variables:
  HEADLESS: "true"

cache:
  paths:
    - .cache
    - venv/

before_script:
  - python -V
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

install-dependencies:
  stage: install
  script:
    - pip install pytest playwright
    - playwright install

default:
  image: mcr.microsoft.com/playwright/python:v1.45.1-jammy
  tags:
    - superpharm
  artifacts:
    when: always
    expire_in: 3 DAYS
    paths:
      - screenshots/
      - target/allure-results/

.pipeline-branch-model:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: manual
  allow_failure: true

Zegarownia-orders:
  extends: .pipeline-branch-model
  stage: Zegarownia
  script:
    - source venv/bin/activate
    - pytest tests/Zegarownia/Orders/GuestUser --env=stage --alluredir=/Users/global/Desktop/Zegarownia/allure_results
